project:
  type: website
  output-dir: docs
website:
  title: "Zuleika Gasimova"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: conference.qmd
        text: Presented Works

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

